//[Pop] Basically, at least until our map guy is able to, all edits to weapon
//placements or ammo placements that need to be done will happen via code, right
//in this file. Checksums will need to be updated if a map file is modified.

class PG12_ChecksumChecks : LevelPostProcessor
{
    protected void Apply(Name checksum, String mapname)
    {
		Console.printf("%s", level.getchecksum());
		switch(checksum)
        {
			//[Pop] Lets add the Garand and M1911 to C1M2 as a test first
            case 'e53a54b7fa7ac1ffb59dbcd297eb9e86':
				AddThing(32310, (-3, -665, 80), SKILLS_ALL);
				
				AddThing(32311, (39, -620, 80), SKILLS_ALL);
				
				AddThing(32313, (-8, -673, 80), SKILLS_ALL);
				AddThing(32313, (4, -658, 80), SKILLS_ALL);
				
				AddThing(32312, (43, -623, 80), SKILLS_ALL);
				AddThing(32312, (37, -625, 80), SKILLS_ALL);
				AddThing(32312, (35, -615, 80), SKILLS_ALL);
				break;
			//[Pop] C2M1 edits
			case '2f68c1fff3b9524e4945a93c4a8f0658':
				//[Pop] Lets put a Box of 9mm in this room near the start as backup
				AddThing(32316, (-3319, 1161, -768), SKILLS_ALL);
				
				//Next up: the PPK
				AddThing(32315, (-3734, 4264, -680), SKILLS_ALL);
				AddThing(32314, (-3702, 4247, -712), SKILLS_ALL);
				break;
        }
    }
}